# Generated by Django 2.2 on 2020-05-11 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_auto_20200511_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='manager',
            new_name='user',
        ),
    ]
